// <auto-generated />
using System;
using GuestHibajelentesEvvegi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuestHibajelentesEvvegi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("assigned_to")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("machine_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("resolved_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("submitted_by")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("assigned_to");

                    b.HasIndex("machine_id");

                    b.HasIndex("submitted_by");

                    b.ToTable("Errors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            assigned_to = "2",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8466),
                            description = "Error description 1",
                            machine_id = 1,
                            resolved_at = new DateTime(2025, 3, 31, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8477),
                            status = 0,
                            submitted_by = "1"
                        },
                        new
                        {
                            Id = 2,
                            assigned_to = "3",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8487),
                            description = "Error description 2",
                            machine_id = 2,
                            resolved_at = new DateTime(2025, 4, 1, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8489),
                            status = 1,
                            submitted_by = "2"
                        },
                        new
                        {
                            Id = 3,
                            assigned_to = "4",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8491),
                            description = "Error description 3",
                            machine_id = 3,
                            resolved_at = new DateTime(2025, 4, 2, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8492),
                            status = 2,
                            submitted_by = "3"
                        },
                        new
                        {
                            Id = 4,
                            assigned_to = "1",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8497),
                            description = "Error description 4",
                            machine_id = 4,
                            resolved_at = new DateTime(2025, 4, 3, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8498),
                            status = 0,
                            submitted_by = "4"
                        });
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("error_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("error_id");

                    b.HasIndex("user_id");

                    b.ToTable("Error_logs");
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.ErrorTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("assigned_to")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("error_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("resolved_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("assigned_to");

                    b.HasIndex("error_id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            assigned_to = "2",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8536),
                            description = "Task 1 for Error 1",
                            error_id = 1,
                            resolved_at = new DateTime(2025, 3, 30, 22, 0, 38, 114, DateTimeKind.Local).AddTicks(8542)
                        },
                        new
                        {
                            Id = 2,
                            assigned_to = "2",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8545),
                            description = "Task 2 for Error 1",
                            error_id = 1,
                            resolved_at = new DateTime(2025, 3, 30, 23, 0, 38, 114, DateTimeKind.Local).AddTicks(8562)
                        },
                        new
                        {
                            Id = 3,
                            assigned_to = "2",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8564),
                            description = "Task 3 for Error 1",
                            error_id = 1,
                            resolved_at = new DateTime(2025, 3, 31, 0, 0, 38, 114, DateTimeKind.Local).AddTicks(8566)
                        },
                        new
                        {
                            Id = 4,
                            assigned_to = "3",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8571),
                            description = "Task 1 for Error 2",
                            error_id = 2,
                            resolved_at = new DateTime(2025, 3, 30, 22, 0, 38, 114, DateTimeKind.Local).AddTicks(8572)
                        },
                        new
                        {
                            Id = 5,
                            assigned_to = "3",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8574),
                            description = "Task 2 for Error 2",
                            error_id = 2,
                            resolved_at = new DateTime(2025, 3, 30, 23, 0, 38, 114, DateTimeKind.Local).AddTicks(8576)
                        },
                        new
                        {
                            Id = 6,
                            assigned_to = "3",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8578),
                            description = "Task 3 for Error 2",
                            error_id = 2,
                            resolved_at = new DateTime(2025, 3, 31, 0, 0, 38, 114, DateTimeKind.Local).AddTicks(8579)
                        },
                        new
                        {
                            Id = 7,
                            assigned_to = "4",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8581),
                            description = "Task 1 for Error 3",
                            error_id = 3,
                            resolved_at = new DateTime(2025, 3, 30, 22, 0, 38, 114, DateTimeKind.Local).AddTicks(8583)
                        },
                        new
                        {
                            Id = 8,
                            assigned_to = "4",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8585),
                            description = "Task 2 for Error 3",
                            error_id = 3,
                            resolved_at = new DateTime(2025, 3, 30, 23, 0, 38, 114, DateTimeKind.Local).AddTicks(8586)
                        },
                        new
                        {
                            Id = 9,
                            assigned_to = "4",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8588),
                            description = "Task 3 for Error 3",
                            error_id = 3,
                            resolved_at = new DateTime(2025, 3, 31, 0, 0, 38, 114, DateTimeKind.Local).AddTicks(8592)
                        },
                        new
                        {
                            Id = 10,
                            assigned_to = "1",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8617),
                            description = "Task 1 for Error 4",
                            error_id = 4,
                            resolved_at = new DateTime(2025, 3, 30, 22, 0, 38, 114, DateTimeKind.Local).AddTicks(8619)
                        },
                        new
                        {
                            Id = 11,
                            assigned_to = "1",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8621),
                            description = "Task 2 for Error 4",
                            error_id = 4,
                            resolved_at = new DateTime(2025, 3, 30, 23, 0, 38, 114, DateTimeKind.Local).AddTicks(8622)
                        },
                        new
                        {
                            Id = 12,
                            assigned_to = "1",
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8624),
                            description = "Task 3 for Error 4",
                            error_id = 4,
                            resolved_at = new DateTime(2025, 3, 31, 0, 0, 38, 114, DateTimeKind.Local).AddTicks(8625)
                        });
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("hall")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8380),
                            hall = "H1",
                            name = "Machine1",
                            status = 0
                        },
                        new
                        {
                            Id = 2,
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8430),
                            hall = "H2",
                            name = "Machine2",
                            status = 1
                        },
                        new
                        {
                            Id = 3,
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8433),
                            hall = "H3",
                            name = "Machine3",
                            status = 0
                        },
                        new
                        {
                            Id = 4,
                            created_at = new DateTime(2025, 3, 30, 21, 0, 38, 114, DateTimeKind.Local).AddTicks(8435),
                            hall = "H4",
                            name = "Machine4",
                            status = 1
                        });
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "XYZ123",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAELzE0Wrf9HOHKgcIumGnnzT3l4CQa9PAc9pN77mgArUJptgJL/fgkfEu/weeyhTwBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ABC123",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "UVW456",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEO/F8wkxerv9DZ2NP1go80NewzhfdYoVr55sVBNKtU95YHZ85dZzQMs9zoKmbAaeQQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DEF456",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "RST789",
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ0vvjT1SYrRYme8Bcf0RVy0XWOjlsFOBeISu2Pi/APVtP1BfC6xKE1b2ExoHBV7YA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GHI789",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "OPQ012",
                            Email = "user4@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@EXAMPLE.COM",
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEC6X/9bLzl4+cfGiFYU95e7PgdjD4qnB4GhPs/XDKcUdei6AFOu65SniU00/Y/gLTQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "JKL012",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.Error", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.User", "assigned_worker")
                        .WithMany()
                        .HasForeignKey("assigned_to")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestHibajelentesEvvegi.Models.Machine", "machine")
                        .WithMany()
                        .HasForeignKey("machine_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestHibajelentesEvvegi.Models.User", "submitting_worker")
                        .WithMany()
                        .HasForeignKey("submitted_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assigned_worker");

                    b.Navigation("machine");

                    b.Navigation("submitting_worker");
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.ErrorLog", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.Error", "base_error")
                        .WithMany()
                        .HasForeignKey("error_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestHibajelentesEvvegi.Models.User", "notified_worker")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("base_error");

                    b.Navigation("notified_worker");
                });

            modelBuilder.Entity("GuestHibajelentesEvvegi.Models.ErrorTask", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.User", "assigned_worker")
                        .WithMany()
                        .HasForeignKey("assigned_to")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestHibajelentesEvvegi.Models.Error", "associated_error")
                        .WithMany()
                        .HasForeignKey("error_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assigned_worker");

                    b.Navigation("associated_error");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestHibajelentesEvvegi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GuestHibajelentesEvvegi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
